name: EAS Production Build (Android & IOS) (EAS)

on:
  workflow_dispatch:

jobs:
  Build:
    name: EAS Production Build (Android & IOS) (EAS)
    runs-on: ubuntu-latest
    steps:
      - name : üì¶ Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name : üì¶ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ‚è±Ô∏è EAS Build
        uses: ./.github/actions/eas-build
        with:
          APP_ENV: production