name: QA Build

on:
  workflow_dispatch:
  # release: // TODO: uncomment this to push new release whit new releases
  #   types: [published]

jobs:
  Build:
    name: Android & IOS QA Build
    runs-on: ubuntu-latest
    steps:
      - name : ğŸ“¦ Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name : ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸ“¦ Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: âš™ï¸ Run Prebuild
        run: pnpm prebuild:staging

      - name: ğŸ“± Run Android Build
        run: pnpm build:staging:android --non-interactive --no-wait --message "QA ${{ github.event.release.tag_name }}"

      - name: ğŸ“± Run IOS Build
        run: pnpm build:staging:ios --non-interactive --auto-submit --no-wait --message "QA ${{ github.event.release.tag_name }}"